name: Tulips CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug-and-test-with-clang:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make debug-all
      - name: build
        run: make build
      - name: test
        run: make test
      - uses: actions/upload-artifact@v4
        with:
          name: clang-tests-artifacts
          path: |
            build/tests/**/*.keys
            build/tests/**/*.log
            build/tests/**/*.pcap
  build-debug-and-test-with-gcc:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      env:
        CC: gcc
        CXX: g++
        CTEST_OUTPUT_ON_FAILURE: 1
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make debug-all
      - name: build
        run: make build
      - name: test
        run: make test
      - uses: actions/upload-artifact@v4
        with:
          name: gcc-tests-artifacts
          path: |
            build/tests/**/*.keys
            build/tests/**/*.log
            build/tests/**/*.pcap
  build-release-with-clang:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make release-all
      - name: build
        run: make build
  build-release-with-gcc:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      env:
        CC: gcc
        CXX: g++
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make release-all
      - name: build
        run: make build
  check-format:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make debug-all
      - name: format
        run: make format-check
  lint:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make debug-all
      - name: lint
        run: make tidy
