name: Tulips CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug-and-test:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      env:
        CTEST_PARALLEL_LEVEL: 2
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make debug-all
      - name: build
        run: make build
      - name: test
        run: make test
  build-release:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      env:
        CTEST_PARALLEL_LEVEL: 2
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make release-all
      - name: build
        run: make build
  check-format:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make debug-all
      - name: format
        run: make format-check
  lint:
    runs-on: ubuntu-latest
    container: 
      image: xenogenics/tulips-builder
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: make debug-all
      - name: lint
        run: make tidy
